#ifndef ERR_HPP
#define ERR_HPP

#define ERR_NOSUCHNICK			401
#define ERR_NOSUCHSERVER		402
#define ERR_NOSUCHCHANNEL		403
#define ERR_CANNOTSENDTOCHAN	404
#define ERR_NOORIGIN			409
#define ERR_NORECIPIENT			411
#define ERR_NOTEXTTOSEND		412
#define ERR_UNKNOWNCOMMAND		421
#define ERR_ERRONEUSNICKNAME	432
#define ERR_NICKNAMEINUSE		433
#define ERR_USERNOTINCHANNEL	441
#define ERR_NOTONCHANNEL		442
#define ERR_USERONCHANNEL		443
#define ERR_NEEDMOREPARAMS		461
#define ERR_ALREADYREGISTRED	462
#define ERR_PASSWDMISMATCH		464
#define ERR_CHANNELISFULL		471
#define ERR_UNKNOWNMODE			472
#define ERR_INVITEONLYCHAN		473
#define ERR_BADCHANNELKEY		475
#define ERR_CHANOPRIVSNEEDED	482
#define ERR_UMODEUNKNOWNFLAG	501
#define ERR_USERSDONTMATCH		502

#endif